### ISSUE TITLE
Update rechart dependency

### ISSUE THREAD

**Issue by kamilkuz** [ahrefs/bs-recharts#16]
I noticed that this library depends on recharts in version: ^1.0.0-beta.10
But recharts is now available in: 1.5.0 (not beta): https://www.npmjs.com/package/recharts
I don't know what changed from 1.0.0 to 1.5.0 but I think it's worth having the latest not-beta version as a dependency.

**Comment by kamilkuz** [comment]
I just wonder that maybe recharts should be peerDependency ?

**Comment by liubko** [comment]
I think we can move it to `peerDependency` (like they do in bs-moment)

CC @feihong @rusty-key

**Comment by rusty-key** [comment]
yeah, it should be peerDependency. 
(sorry for the late response)

**Comment by liubko** [comment]
published v0.2.14
