### ISSUE TITLE
Add compatibility to JSX v3

### ISSUE THREAD

**Issue by zbaylin** [ahrefs/bs-recharts#19]
Right now it's not possible to use the chart components in any component that uses JSX3. There is a convenience function specified here that can do this automatically: https://reasonml.github.io/reason-react/docs/en/jsx. However, I can't seem to get it to work. I always run into this error:
`This expression's type contains type variables that can't be generalized:`. Hopefully someone smarter than me can figure out the issue.

**Comment by arjun-menon** [comment]
@ahrefs Facing the same problem here.... @tmattio seems to have ported it over, so it's possibly only necessary to merge in his changes, c.f.: https://github.com/tmattio/bs-recharts

**Comment by liubko** [comment]
Published 3.0.0 please take a look. Closing this one
