### ISSUE TITLE
Have to clean artifacts on each compile

### ISSUE THREAD

**Issue by ccapndave** [ahrefs/bs-recharts#5]
When using `bs-recharts` every time I make a file change I get an error saying:

```
Failed to compile.

./src/index.re
Module build failed: Error: We've found a bug for you!
  /Users/dave/Projects/Reason/magicstats/src/Chart.re

  It's possible that your build is stale.
  Try to clean the artifacts and build again?

  Here's the original error message
  The files /Users/dave/Projects/Reason/magicstats/node_modules/reason-react/lib/ocaml/reasonReact.cmi
  and /Users/dave/Projects/Reason/magicstats/node_modules/@ahrefs/bs-recharts/lib/ocaml/bsRecharts__ResponsiveContainer.cmi
    at Array.map (<anonymous>)s over interface ReasonReact
    at <anonymous>
```

If I run `bsb -clean` then it works, until I change a file at which point it gives me the error above again.  Strangely, if I use the development version (with `yarn link`) then this doesn't happen.

Atom also gives me this error on the line `open BsRecharts`:

```
Error: The files /Users/dave/Projects/Reason/magicstats/node_modules/reason-react/lib/ocaml/ReasonReact.cmi
and /Users/dave/Projects/Reason/bs-recharts/lib/ocaml/BsRecharts__ResponsiveContainer.cmi
make inconsistent assumptions over interface ReasonReact```
```

Sorry if I have done something stupid, I am a Reason noob ;)

**Comment by ccapndave** [comment]
I found that this doesn't happen with ReasonReact 0.3.2 - but it does happen with the latest version (0.4.2).

**Comment by liubko** [comment]
oops.. this issue slipped under the radar. 
Is it still a problem?

**Comment by liubko** [comment]
it's been a while, closing. if the issue still occurs, please feel free to reopen
