### ISSUE TITLE
Float pixels/percents

### ISSUE THREAD

**Issue by rusty-key** [ahrefs/bs-recharts#7]
Both pixels and percents can be floats
https://github.com/ahrefs/bs-recharts/blob/master/src/BsRecharts__Utils.re#L51-L61

**Comment by rusty-key** [comment]
@liubko, I think we should just change types there to floats. Another way would be to add more variants like `FloatPx` and `FloatPrc`. What do you think?

**Comment by liubko** [comment]
let's update `PxOrPrc`
```
...
  type arg =
    | Px(float)
    | Prc(float);
...
```
